### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by telmen** [gorhom/react-native-portal#10]
Hi, thanks for the lib.

Is there a reason that there are two `useEffect` hooks used and not combined in one?  https://github.com/gorhom/react-native-portal/blob/master/src/components/portal/Portal.tsx#L31

**Comment by futuredayv** [comment]
Hey @telmen 👋

I asked the same question when I first saw it but it seems he prefered to handle `didMount` and `didUnmount` cycles seperately. Since this is an open source project, it might be more understandable for developers who uses classes.

But I would suggest using effect once and just pass named functions. @gorhom 

```ts
useEffect(() => {
  onMount();

  return onUnmount;
}, [])
```

**Comment by telmen** [comment]
Closing this.
